# -*- coding: utf-8 -*-
"""8-3 მექვაბიშვილი ირაკლი #6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19K1F-N7-FEEEMRGjKjNZaY5GdMFqChhR
"""

import random
a = random.randint(10**11, 10**12)
mn = 10
mx = 0
print(a)
while (a>0):
    k = a%10
    mx = max(k, mx)
    mn = min(k, mn)
    a //= 10
print((mx+mn)**2)