# -*- coding: utf-8 -*-
"""8-3 მექვაბიშვილი ირაკლი #5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19K1F-N7-FEEEMRGjKjNZaY5GdMFqChhR
"""

import math 
x1 = int(input("x1 ")) 
x2 = int(input("x2 ")) 
y1 = int(input("y1 ")) 
y2 =int(input("y2 ")) 
print(math.sqrt((x2-x1)**2 + (y2 - y1)**2))