# -*- coding: utf-8 -*-
"""8-3 მექვაბიშვილი ირაკლი #3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19K1F-N7-FEEEMRGjKjNZaY5GdMFqChhR
"""

import random
a = random.randint(100, 999)

minutes = a//60

seconds = a%60
print(a)
print(str(minutes) + " minutes and " + str(seconds) + " seconds")