# -*- coding: utf-8 -*-
"""8-3 მექვაბიშვილი ირაკლი #4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19K1F-N7-FEEEMRGjKjNZaY5GdMFqChhR
"""

a = 2.59
b = -8.92
d = (2*b)/(a**b)
c = (a - 2*b)/(d**2)
r = (2.79*a + 3*d)/(b**2 - 2*a*c)

print((4/(3*r+4))-9*(a+b*c)+((3+d*(2+a))/(a+b*d)))