# -*- coding: utf-8 -*-
"""8-3 მექვაბიშვილი ირაკლი #2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19K1F-N7-FEEEMRGjKjNZaY5GdMFqChhR
"""

km = 14.0
miles = km/1.6
minutes = 45.5

miles_minute = miles/minutes
 
miles_hour = miles_minute * 60

print(str(miles_hour) + " miles/hour")