# -*- coding: utf-8 -*-
"""8-3 მექვაბიშვილი ირაკლი #1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19K1F-N7-FEEEMRGjKjNZaY5GdMFqChhR
"""

print (((9.5*4.5)-(2.5*3))/(45.5-3.5))